<script lang="ts">
  // Renders parsed markdown as real DOM: true <table>, lists, headings, safe
  // links. Terminal soul stays in the chrome; content gets the web — charts
  // and session-cwd images included.
  import { parseMarkdown, type Inline } from "../lib/markdown";
  import { app } from "../lib/state.svelte";

  let { src, sessionId = "" }: { src: string; sessionId?: string } = $props();

  const blocks = $derived(parseMarkdown(src));
  const canFiles = $derived(app.caps.includes("files_read"));
  // Subresource loads (<img>/<iframe>) send no Authorization header; the file
  // endpoint accepts ?t=<token> instead. Read once — the page already holds
  // this value in localStorage.
  const fileToken = typeof localStorage !== "undefined" ? (localStorage.getItem("dextui.token") ?? "") : "";
  // href → true once the browser reports a failed image load: an actionable
  // chip instead of silent alt-text soup when a file 404s.
  let broken = $state<Record<string, boolean>>({});

  // Models emit file paths in several shapes — relative ("qc_charts/x.png"),
  // absolute file URIs ("file:///home/demo/dextui-workspace/qc_charts/x.png"),
  // and WSL UNC URIs ("file://wsl.localhost/Ubuntu/home/demo/..."). Only paths
  // under the session cwd are servable; relativize everything to that.
  function normalizeHref(href: string): string {
    let p = href;
    if (p.startsWith("file://")) {
      p = p.slice(7);
      const wsl = /^wsl\.localhost\/[^/]+(\/.*)$/.exec(p);
      if (wsl && wsl[1]) p = wsl[1];
    }
    try {
      p = decodeURIComponent(p);
    } catch {
      /* keep raw */
    }
    const cwd = app.sessions.find((s) => s.id === sessionId)?.cwd ?? "";
    if (cwd && p.startsWith(`${cwd}/`)) p = p.slice(cwd.length + 1);
    return p.replace(/^\//, "");
  }

  // Path-shaped URL so an HTML artifact's nested relative images resolve.
  function fileUrl(href: string): string {
    const path = normalizeHref(href)
      .split("/")
      .map(encodeURIComponent)
      .join("/");
    return `/sessions/${encodeURIComponent(sessionId)}/file/${path}?t=${encodeURIComponent(fileToken)}`;
  }

  const isHtmlArtifact = (href: string): boolean => /\.html?$/i.test(href);
</script>

{#snippet inline(parts: Inline[])}
  {#each parts as tk, i (i)}
    {#if tk.t === "code"}<code class="ic">{tk.s}</code>{:else if tk.t === "bold"}<strong>{tk.s}</strong>{:else if tk.t === "italic"}<em>{tk.s}</em>{:else if tk.t === "link"}<a href={tk.href} target="_blank" rel="noopener noreferrer">{tk.s}</a>{:else if tk.t === "image"}
      {#if /^https?:\/\//.test(tk.href)}
        <!-- model-chosen remote URLs stay links: never fetch them silently -->
        <a href={tk.href} target="_blank" rel="noopener noreferrer">{tk.s || tk.href}</a>
      {:else if !sessionId || !canFiles}
        <code class="ic">{tk.href}</code>
      {:else if isHtmlArtifact(tk.href)}
        <!-- HTML artifact: self-contained dashboard in a sandboxed opaque-origin frame -->
        <span class="md-artifact" data-agent-id="markdown.artifact">
          <span class="md-artifact-head">
            <span class="st-cyan">▤ artifact</span>
            <span class="dim md-artifact-name">{tk.s || tk.href}</span>
            <a class="act" href={fileUrl(tk.href)} target="_blank" rel="noopener noreferrer">open ↗</a>
          </span>
          <iframe sandbox="allow-scripts" loading="lazy" title={tk.s || tk.href} src={fileUrl(tk.href)}></iframe>
        </span>
      {:else if broken[tk.href]}
        <span class="md-imgmiss" data-agent-id="markdown.image.missing">✗ image not found under the session workspace: {tk.href}</span>
      {:else}
        <span class="md-img" data-agent-id="markdown.image">
          <img src={fileUrl(tk.href)} alt={tk.s} loading="lazy" onerror={() => (broken[tk.href] = true)} />
          {#if tk.s}<span class="faint md-imgcap">{tk.s}</span>{/if}
        </span>
      {/if}
    {:else}{tk.s}{/if}
  {/each}
{/snippet}

<div class="md">
  {#each blocks as b, bi (bi)}
    {#if b.kind === "heading"}
      <svelte:element this={`h${Math.min(Math.max(b.level, 1), 4)}`} class="md-h">
        {@render inline(b.inline)}
      </svelte:element>
    {:else if b.kind === "para"}
      <p class="md-p">{@render inline(b.inline)}</p>
    {:else if b.kind === "code"}
      <div class="md-code">
        {#if b.lang}<span class="md-lang">{b.lang}</span>{/if}
        <pre>{b.text}</pre>
      </div>
    {:else if b.kind === "chart"}
      <!-- svg is machine-generated by charts.ts: dynamics escaped/validated there -->
      <div class="md-chart" data-agent-id="markdown.chart">
        {@html b.svg}
      </div>
    {:else if b.kind === "art"}
      <pre class="md-art">{b.text}</pre>
    {:else if b.kind === "list"}
      {#if b.ordered}
        <ol class="md-list">
          {#each b.items as it, ii (ii)}
            <li>
              {@render inline(it.inline)}
              {#if it.sub.length > 0}
                <ul class="md-list">
                  {#each it.sub as sub, si (si)}
                    <li>{@render inline(sub.inline)}</li>
                  {/each}
                </ul>
              {/if}
            </li>
          {/each}
        </ol>
      {:else}
        <ul class="md-list">
          {#each b.items as it, ii (ii)}
            <li>
              {@render inline(it.inline)}
              {#if it.sub.length > 0}
                <ul class="md-list">
                  {#each it.sub as sub, si (si)}
                    <li>{@render inline(sub.inline)}</li>
                  {/each}
                </ul>
              {/if}
            </li>
          {/each}
        </ul>
      {/if}
    {:else if b.kind === "table"}
      <div class="md-tablewrap">
        <table class="md-table">
          <thead>
            <tr>
              {#each b.head as cell, ci (ci)}
                <th style={`text-align:${b.align[ci] === "r" ? "right" : b.align[ci] === "c" ? "center" : "left"}`}>
                  {@render inline(cell)}
                </th>
              {/each}
            </tr>
          </thead>
          <tbody>
            {#each b.rows as row, ri (ri)}
              <tr>
                {#each row as cell, ci (ci)}
                  <td style={`text-align:${b.align[ci] === "r" ? "right" : b.align[ci] === "c" ? "center" : "left"}`}>
                    {@render inline(cell)}
                  </td>
                {/each}
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    {:else if b.kind === "quote"}
      <blockquote class="md-quote">{@render inline(b.inline)}</blockquote>
    {:else if b.kind === "hr"}
      <hr class="md-hr" />
    {/if}
  {/each}
</div>

<style>
  .md {
    display: flex;
    flex-direction: column;
    gap: 6px;
    min-width: 0;
  }
  .md-h {
    font-size: 13px;
    font-weight: bold;
    color: var(--fg);
    margin-top: 6px;
  }
  .md :is(h1, h2).md-h {
    font-size: 14px;
    border-bottom: 1px solid var(--line);
    padding-bottom: 2px;
  }
  .md-p {
    white-space: pre-line;
    overflow-wrap: break-word;
  }
  .ic {
    background: var(--bg2);
    padding: 0 4px;
    color: var(--orange);
  }
  a {
    color: var(--blue);
    text-decoration: none;
  }
  a:hover {
    text-decoration: underline;
    text-underline-offset: 3px;
  }
  .md-code {
    position: relative;
    border-left: 2px solid var(--line);
    background: var(--bg1);
  }
  .md-code pre {
    padding: 6px 10px;
    overflow-x: auto;
    font-size: 12px;
  }
  .md-lang {
    position: absolute;
    top: 2px;
    right: 8px;
    color: var(--faint);
    font-size: 10px;
    user-select: none;
  }
  .md-art {
    overflow-x: auto;
    white-space: pre;
    color: var(--dim);
    font-size: 12px;
    line-height: 1.3;
  }
  .md-chart {
    border: 1px solid var(--line);
    background: var(--bg1);
    padding: 8px 12px;
  }
  .md-img {
    display: inline-flex;
    flex-direction: column;
    gap: 2px;
    max-width: 100%;
  }
  .md-img img {
    max-width: min(480px, 100%);
    max-height: 360px;
    border: 1px solid var(--line);
    background: var(--bg1);
  }
  .md-imgcap {
    font-size: 10px;
  }
  .md-artifact {
    display: flex;
    flex-direction: column;
    width: 100%;
    max-width: 100%;
    border: 1px solid var(--line);
    background: var(--bg1);
  }
  .md-artifact-head {
    display: flex;
    gap: 8px;
    align-items: center;
    border-bottom: 1px solid var(--line);
    padding: 3px 8px;
  }
  .md-artifact-head .act {
    margin-left: auto;
  }
  .md-artifact-name {
    flex: 1;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: 11.5px;
  }
  .md-artifact iframe {
    display: block;
    width: 100%;
    height: 560px;
    border: 0;
    background: #0b0d10;
  }
  .md-imgmiss {
    display: inline-block;
    max-width: 100%;
    overflow-wrap: anywhere;
    border: 1px solid color-mix(in srgb, var(--red, #f85149) 45%, var(--line));
    color: var(--red, #f85149);
    padding: 2px 8px;
    font-size: 11.5px;
  }
  .md-list {
    padding-left: 2ch;
    display: flex;
    flex-direction: column;
    gap: 2px;
    list-style: none;
  }
  ul.md-list > li::before {
    content: "• ";
    color: var(--faint);
  }
  ol.md-list {
    counter-reset: md;
  }
  ol.md-list > li {
    counter-increment: md;
  }
  ol.md-list > li::before {
    content: counter(md) ". ";
    color: var(--faint);
  }
  .md-list .md-list {
    margin-top: 2px;
  }
  .md-tablewrap {
    overflow-x: auto;
    max-width: 100%;
  }
  .md-table {
    border-collapse: collapse;
    font-size: 12.5px;
  }
  .md-table th,
  .md-table td {
    border: 1px solid var(--line);
    padding: 3px 10px;
    vertical-align: top;
  }
  .md-table th {
    background: var(--bg1);
    color: var(--cyan);
    font-weight: bold;
    white-space: nowrap;
  }
  .md-table tbody tr:nth-child(even) {
    background: color-mix(in srgb, var(--bg1) 55%, transparent);
  }
  .md-quote {
    border-left: 2px solid var(--faint);
    padding-left: 10px;
    color: var(--dim);
    font-style: italic;
  }
  .md-hr {
    border: 0;
    border-top: 1px solid var(--line);
    margin: 4px 0;
  }
</style>
